-- MySQL Script generated by MySQL Workbench
-- Sat Apr 18 23:33:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campus` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `addr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `campus_id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `id` VARCHAR(20) NOT NULL,
  `id_type` ENUM('id_card', 'passport') NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gender` ENUM('M', 'F') NOT NULL,
  `birth` DATE NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `family_addr` VARCHAR(45) NULL,
  `family_zipcode` VARCHAR(45) NULL,
  `family_tele` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `id` VARCHAR(10) NOT NULL,
  `person_id` VARCHAR(20) NOT NULL,
  `enter_year_month` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `title` ENUM('prof', 'vice_prof') NOT NULL,
  `Major_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `teacher_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Teacher_Person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_Teacher_Major1_idx` (`Major_id` ASC) VISIBLE,
  CONSTRAINT `fk_Teacher_Person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_Major1`
    FOREIGN KEY (`Major_id`)
    REFERENCES `mydb`.`Major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Major` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `addr` VARCHAR(45) NOT NULL,
  `campus_id` VARCHAR(10) NOT NULL,
  `charge_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `major_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Major_Campus1_idx` (`campus_id` ASC) VISIBLE,
  INDEX `fk_Major_Teacher1_idx` (`charge_id` ASC) VISIBLE,
  CONSTRAINT `fk_Major_Campus1`
    FOREIGN KEY (`campus_id`)
    REFERENCES `mydb`.`Campus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Major_Teacher1`
    FOREIGN KEY (`charge_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `class_id` VARCHAR(10) NOT NULL,
  `class_name` VARCHAR(45) NOT NULL,
  `found_date` DATETIME NOT NULL,
  `year` YEAR NOT NULL,
  `major_id` VARCHAR(10) NOT NULL,
  `charge_teacher_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`class_id`),
  UNIQUE INDEX `class_id_UNIQUE` (`class_id` ASC) VISIBLE,
  INDEX `fk_Class_Major1_idx` (`major_id` ASC) VISIBLE,
  INDEX `fk_Class_Teacher1_idx` (`charge_teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Class_Major1`
    FOREIGN KEY (`major_id`)
    REFERENCES `mydb`.`Major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Class_Teacher1`
    FOREIGN KEY (`charge_teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `id` VARCHAR(10) NOT NULL,
  `person_id` VARCHAR(20) NOT NULL,
  `enter_year_month` DATE NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `class_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `student_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Student_Person1_idx` (`person_id` ASC) VISIBLE,
  INDEX `fk_Student_Class1_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `mydb`.`Person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Class1`
    FOREIGN KEY (`class_id`)
    REFERENCES `mydb`.`Class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `id` VARCHAR(10) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `assessment_method` ENUM('exam', 'reply') NOT NULL,
  `Major_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `course_id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Course_Major1_idx` (`Major_id` ASC) VISIBLE,
  CONSTRAINT `fk_Course_Major1`
    FOREIGN KEY (`Major_id`)
    REFERENCES `mydb`.`Major` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_instance` (
  `course_id` VARCHAR(10) NOT NULL,
  `instance_id` VARCHAR(45) NOT NULL,
  `teacher_id` VARCHAR(10) NOT NULL,
  `open_year` YEAR NOT NULL,
  `term` ENUM('spring', 'full') NOT NULL,
  `time` INT NOT NULL,
  INDEX `fk_Course_instance_Course1_idx` (`course_id` ASC) VISIBLE,
  PRIMARY KEY (`instance_id`),
  INDEX `fk_Course_instance_Teacher1_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Course_instance_Course1`
    FOREIGN KEY (`course_id`)
    REFERENCES `mydb`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_instance_Teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `mydb`.`Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course_selection`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course_selection` (
  `id` VARCHAR(20) NOT NULL,
  `course_instance_id` VARCHAR(45) NOT NULL,
  `student_id` VARCHAR(10) NOT NULL,
  `score` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Course_selection_Course_instance1_idx` (`course_instance_id` ASC) VISIBLE,
  INDEX `fk_Course_selection_Student1_idx` (`student_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_Course_selection_Course_instance1`
    FOREIGN KEY (`course_instance_id`)
    REFERENCES `mydb`.`Course_instance` (`instance_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_selection_Student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Adjustment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Adjustment` (
  `id` VARCHAR(20) NOT NULL,
  `from_class_id` VARCHAR(10) NOT NULL,
  `to_class_id` VARCHAR(10) NOT NULL,
  `type` ENUM('change_major', 'downgrade') NOT NULL,
  `date` DATE NOT NULL,
  `Student_id` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Adjustment_Class1_idx` (`from_class_id` ASC) VISIBLE,
  INDEX `fk_Adjustment_Class2_idx` (`to_class_id` ASC) VISIBLE,
  INDEX `fk_Adjustment_Student1_idx` (`Student_id` ASC) VISIBLE,
  CONSTRAINT `fk_Adjustment_Class1`
    FOREIGN KEY (`from_class_id`)
    REFERENCES `mydb`.`Class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Adjustment_Class2`
    FOREIGN KEY (`to_class_id`)
    REFERENCES `mydb`.`Class` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Adjustment_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `mydb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Degrade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Degrade` (
  `reason` ENUM('suspend', 'support_teaching') NOT NULL,
  `Adjustment_id` VARCHAR(20) NOT NULL,
  INDEX `fk_Degrade_Adjustment1_idx` (`Adjustment_id` ASC) VISIBLE,
  PRIMARY KEY (`Adjustment_id`),
  CONSTRAINT `fk_Degrade_Adjustment1`
    FOREIGN KEY (`Adjustment_id`)
    REFERENCES `mydb`.`Adjustment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Change_major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Change_major` (
  `relation_change` ENUM('Yes', 'No', 'None') NOT NULL,
  `Adjustment_id` VARCHAR(20) NOT NULL,
  INDEX `fk_table2_Adjustment1_idx` (`Adjustment_id` ASC) VISIBLE,
  PRIMARY KEY (`Adjustment_id`),
  CONSTRAINT `fk_table2_Adjustment1`
    FOREIGN KEY (`Adjustment_id`)
    REFERENCES `mydb`.`Adjustment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
